title: Semantic Versioning
descriptions: A simple set of rules and requirements that dictate how version numbers are assigned and incremented
languages:
  en: English
versions:
  - 11..
current_version: 11..
author: Kjeld Schmidt
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
defaults:
  - scope:
      path: ''
    values:
      layout: default

baseurl: /
url: http://unaver.org/
